package com.helospark.spark.converter.handlers.domain;

public enum FieldCollectorResultKind {
    SOURCE_CONTAINS_DESTIONATION_DOES_NOT,
    DESTIONATION_CONTAINS_SOURCE_DOES_NOT,
    REFERENCE_COPY,
    OPTIONAL_WRAP,
    OPTIONAL_UNWRAP,
    CONVERTER_REQUIRED,
    CONVERTER_WITH_OPTIONAL_REQUIRED
}
